apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursework2
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coursework2
  template:
    metadata:
      labels:
        app: coursework2
    spec:
      containers:
      - name: coursework2
        image: dtudor200/coursework2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---          
apiVersion: v1
kind: Service
metadata:
  name: cw-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: coursework2
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
