apiVersion: apps/v1
kind: Deployment
metadata:
  name: coursework2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coursework2
  template:
    metadata:
      labels:
        app: coursework2
    spec:
      containers:
      - name: coursework2
        image: dtudor200/coursework2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
